const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "./images/shops/shops-1.png",
      name: "Mỳ ý",
      price: "180",
      discount: "25",
    },
    {
      id: 8,
      cover: "./images/shops/shops-2.png",
      name: "Hiso Party",
      price: "120",
      discount: "10",
    },
    {
      id: 9,
      cover: "./images/shops/shops-3.png",
      name: "Cháo",
      price: "20",
      discount: "50 ",
    },
    {
      id: 10,
      cover: "./images/shops/shops-4.png",
      name: "Cơm Tấm",
      price: "99",
      discount: "10 ",
    },
    {
      id: 11,
      cover: "./images/shops/shops-5.png",
      name: "Thịt",
      price: "80",
      discount: "20 ",
    },
    {
      id: 12,
      cover: "./images/shops/shops-7.png",
      name: "Bánh Bao",
      price: "25",
      discount: "20 ",
    },
    {
      id: 13,
      cover: "./images/shops/shops-8.png",
      name: "Weekend Treats",
      price: "60",
      discount: "5 ",
    },
    {
      id: 14,
      cover: "./images/shops/shops-9.png",
      name: "Đồ Uống Lạnh",
      price: "20",
      discount: "10",
    },
    {
      id: 15,
      cover: "./images/shops/shops-10.png",
      name: "Rau Trộn",
      price: "5",
      discount: "21",
    },
    {
      id: 16,
      cover: "./images/shops/shops-11.png",
      name: "Tà Tưa",
      price: "50",
      discount: "12",
    },
    {
      id: 17,
      cover: "./images/shops/shops-12.png",
      name: "Hủ Tiếu",
      price: "15",
      discount: "23",
    },
    {
      id: 18,
      cover: "./images/shops/shops-13.png",
      name: "Gà Rán",
      price: "35",
      discount: "23",
    },
    {
      id: 19,
      cover: "./images/shops/shops-14.png",
      name: "Bánh Mì",
      price: "15",
      discount: "53",
    },
    {
      id: 20,
      cover: "./images/shops/shops-15.png",
      name: "Pizza",
      price: "120",
      discount: "52",
    },
    {
      id: 21,
      cover: "./images/shops/shops-16.png",
      name: "Hamburger",
      price: "50",
      discount: "12",
    },
    {
      id: 22,
      cover: "./images/shops/shops-17.png",
      name: "Cơm",
      price: "25",
      discount: "26",
    },
  ],
}
export default Sdata
